/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ?q= searches name and email. */
        get: operations["get_api_admin_team_list"];
        put?: never;
        /** Invites an assistant: they get an email to set their password. */
        post: operations["post_api_admin_team_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/team/{id}/resend-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A new invitation link, for someone who has not set their password yet. */
        post: operations["post_api_admin_team_resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disables an assistant: they are signed out at their next request. Nothing is deleted. */
        delete: operations["delete_api_admin_team_disable"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/team/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_team_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_invitation_lookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_invitation_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** {uiTheme?}: "light", "dark" or "system". */
        patch: operations["patch_api_me_preferences"];
        trace?: never;
    };
    "/api/platform/impersonatable-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_platform_impersonatable_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_portal_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TeamMemberOutput: {
            id: string;
            email: string;
            fullName: string;
            /** "owner" or "assistant". */
            role: string;
            active: boolean;
            /** "active" (has a password), "invited" (link sent, not used yet) or "none". */
            loginStatus: string;
            /** ISO 8601; null until they first sign in. */
            lastSignInAt?: string | null;
        };
        InvitationOutput: {
            email: string;
            fullName: string;
            /** "super_admin", "owner", "assistant" or "client". */
            role: string;
            accountName?: string | null;
            /** A client signs in at /<slug>/portal; null for a super admin. */
            accountSlug?: string | null;
        };
        MeAccountOutput: {
            id: string;
            name: string;
            /** The first segment of its public URLs: /<slug>, /<slug>/portal. */
            slug: string;
            country: string;
            currency: string;
            locale: string;
            timezone: string;
        };
        ImpersonatorOutput: {
            id: string;
            email: string;
            fullName: string;
        };
        MeOutput: {
            id: string;
            email: string;
            fullName: string;
            roles: string[];
            /** The consultant's account; null for a super admin. */
            account?: components["schemas"]["MeAccountOutput"] | null;
            /** The person at the screen's own theme: the super admin's while they act as someone. */
            uiTheme: string;
            /** null unless a super admin is acting as this user */
            impersonator?: components["schemas"]["ImpersonatorOutput"] | null;
        };
        MePreferencesOutput: {
            /** "light", "dark" or "system" (follow the device). */
            uiTheme: string;
        };
        ImpersonatableAccountOutput: {
            id: string;
            name: string;
        };
        ImpersonatableUserOutput: {
            id: string;
            email: string;
            fullName: string;
            /** "owner" or "assistant". */
            role: string;
            account: components["schemas"]["ImpersonatableAccountOutput"];
        };
        TokenOutput: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_admin_team_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TeamMemberOutput"][];
                        total: number;
                        page: number;
                        perPage: number;
                    };
                };
            };
        };
    };
    post_api_admin_team_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOutput"];
                };
            };
        };
    };
    post_api_admin_team_resend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOutput"];
                };
            };
        };
    };
    delete_api_admin_team_disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOutput"];
                };
            };
        };
    };
    post_api_admin_team_enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOutput"];
                };
            };
        };
    };
    post_api_invitation_lookup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOutput"];
                };
            };
        };
    };
    post_api_invitation_accept: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutput"];
                };
            };
        };
    };
    patch_api_me_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MePreferencesOutput"];
                };
            };
        };
    };
    get_api_platform_impersonatable_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ImpersonatableUserOutput"][];
                    };
                };
            };
        };
    };
    post_api_portal_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOutput"];
                };
            };
        };
    };
}
